- name: k8s
  become: true
  become_method: sudo
  vars:
  hosts: microk8s
  roles:
    - microk8s
  serial: "{{ batch_size|default(1) }}"

# no_log: '{{ no_log_ansible|default(False) }}'

# environment:
#   HTTP_PROXY: "{{ http_proxy }}"
#   HTTPS_PROXY: "{{ https_proxy }}"
#   NO_PROXY: "{{ no_proxy }}"
#   http_proxy: "{{ http_proxy }}"
#   https_proxy: "{{ https_proxy }}"
#   no_proxy: "{{ no_proxy }}"
