
# users
admin_users:
  - epcim
autom_users: #automation (no sudo for root)
  - ops

# upgrade
upgrade: false

# hardening
hardening_disable_coredumps: true
allow_node_restart: false

# coredump
#kcd_version: "0.2.7"

opt_bin_path: /opt/bin
