- name: be sure the dependencies are installed
  yum:
    state: latest
    name:
      - ca-certificates
      - python3
      - python-libvirt
      - python-lxml
      - qemu-kvm
      - libvirt-daemon-system
      - libvirt-clients
      - bridge-utils
 
