---
- name: add OS specific variables
  ansible.builtin.include_vars: "{{ lookup('first_found', restic_os_variables) }}"

- name: perform optional versionscheck
  ansible.builtin.include_tasks: 'versioncheck.yml'
  when: submodules_versioncheck | bool

- name: make sure restic is available
  ansible.builtin.include_tasks: 'preperation.yml'

- name: make sure restic is installed
  ansible.builtin.include_tasks: 'install.yml'
  when: not restic_executable.stat.exists or not restic_installed.stat.exists

- name: initialize restic repo(s)
  ansible.builtin.include_tasks: 'configure.yml'

- name: create backup script
  ansible.builtin.include_tasks: 'backup.yml'
  loop_control:
    loop_var: loop_distribution
  vars:
    distribution: '{{ ansible_distribution }}'
    distribution_version: '{{ ansible_distribution_version }}'
    distribution_major_version: '{{ ansible_distribution_major_version }}'

- name: schedule restic backup
  ansible.builtin.include_tasks: 'schedule.yml'
  loop_control:
    loop_var: loop_distribution
  vars:
    distribution: '{{ ansible_distribution }}'
    distribution_version: '{{ ansible_distribution_version }}'
    distribution_major_version: '{{ ansible_distribution_major_version }}'
