---

- name: be sure we have the latest version of all packages
  apt:
    name: "*"
    state: latest
    update_cache: yes
  when: upgrade
  tags: upgrade

  #- name: be sure the dependencies are installed
  #  apt:
  #    state: latest
  #    name:
  #      - ca-certificates
  #      - python3
  #      - python3-pip
  #      - auditd
  #      - audispd-plugins
  #      - parted

