
# microk8s
# https://github.com/istvano/ansible_role_microk8s/blob/master/defaults/main.yml
microk8s_version: "1.23/stable"
microk8s_dns_resolvers: 172.31.1.1,8.8.8.8
registry_size: 20Gi
microk8s_plugins:
  dashboard: false
  dns: "{{ microk8s_dns_resolvers }}"
  helm3: true
  #host-access: true
  #ingress: true
  metrics-server: true
  #rbac: true
  registry: false #"size={{ registry_size }}"   
  storage: true
  traefik: false
  prometheus: false
#users: ["epcim"]
microk8s_enable_HA: true # NOTE, enable on joined nodes
microk8s_group_HA: "microk8s"
#microk8s_ip_regex_HA: "([0-9]{1,3}[\\.]){3}[0-9]{1,3}"
# regex to select IP address for joining nodes in HA setup

