var_sshd_set_keepalive: !!str 0
sshd_idle_timeout_value: !!str 300
sshd_approved_macs: !!str hmac-sha2-512,hmac-sha2-256,hmac-sha1,hmac-sha1-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com
rsyslog_remote_loghost_address: !!str ""
sysctl_net_ipv4_conf_all_accept_redirects_value: !!str 0
sysctl_net_ipv4_conf_all_accept_source_route_value: !!str 0
sysctl_net_ipv4_conf_all_log_martians_value: !!str 1
sysctl_net_ipv4_conf_all_rp_filter_value: !!str 1
sysctl_net_ipv4_conf_all_secure_redirects_value: !!str 0
sysctl_net_ipv4_conf_default_accept_redirects_value: !!str 0
sysctl_net_ipv4_conf_default_accept_source_route_value: !!str 0
sysctl_net_ipv4_conf_default_log_martians_value: !!str 1
sysctl_net_ipv4_conf_default_rp_filter_value: !!str 1
sysctl_net_ipv4_conf_default_secure_redirects_value: !!str 0
sysctl_net_ipv4_icmp_echo_ignore_broadcasts_value: !!str 1
sysctl_net_ipv4_icmp_ignore_bogus_error_responses_value: !!str 1
sysctl_net_ipv4_tcp_syncookies_value: !!str 1
sysctl_net_ipv6_conf_all_accept_ra_value: !!str 0
sysctl_net_ipv6_conf_all_accept_redirects_value: !!str 0
sysctl_net_ipv6_conf_all_accept_source_route_value: !!str 0
sysctl_net_ipv6_conf_default_accept_ra_value: !!str 0
sysctl_net_ipv6_conf_default_accept_redirects_value: !!str 0
sysctl_net_ipv6_conf_default_accept_source_route_value: !!str 0
var_selinux_policy_name: !!str targeted
var_selinux_state: !!str enforcing
var_account_disable_post_pw_expiration: !!str 30
var_accounts_password_warn_age_login_defs: !!str 7
var_accounts_minimum_age_login_defs: !!str 7 # max_age CIS req. max. 365, other 90
var_accounts_maximum_age_login_defs: !!str 99999
var_accounts_passwords_pam_faillock_unlock_time: !!str 900
var_password_pam_unix_remember: !!str 5
var_accounts_passwords_pam_faillock_deny: !!str 5
var_password_pam_minlen: !!str 14
var_password_pam_dcredit: !!str -1
var_password_pam_lcredit: !!str -1
var_password_pam_ucredit: !!str -1
var_password_pam_retry: !!str 3
login_banner_text: !!str --[\s\n]+WARNING[\s\n]+--[\s\n]*This[\s\n]+system[\s\n]+is[\s\n]+for[\s\n]+the[\s\n]+use[\s\n]+of[\s\n]+authorized[\s\n]+users[\s\n]+only.[\s\n]+Individuals[\s\n]*using[\s\n]+this[\s\n]+computer[\s\n]+system[\s\n]+without[\s\n]+authority[\s\n]+or[\s\n]+in[\s\n]+excess[\s\n]+of[\s\n]+their[\s\n]*authority[\s\n]+are[\s\n]+subject[\s\n]+to[\s\n]+having[\s\n]+all[\s\n]+their[\s\n]+activities[\s\n]+on[\s\n]+this[\s\n]+system[\s\n]*monitored[\s\n]+and[\s\n]+recorded[\s\n]+by[\s\n]+system[\s\n]+personnel.[\s\n]+Anyone[\s\n]+using[\s\n]+this[\s\n]*system[\s\n]+expressly[\s\n]+consents[\s\n]+to[\s\n]+such[\s\n]+monitoring[\s\n]+and[\s\n]+is[\s\n]+advised[\s\n]+that[\s\n]*if[\s\n]+such[\s\n]+monitoring[\s\n]+reveals[\s\n]+possible[\s\n]+evidence[\s\n]+of[\s\n]+criminal[\s\n]+activity[\s\n]*system[\s\n]+personal[\s\n]+may[\s\n]+provide[\s\n]+the[\s\n]+evidence[\s\n]+of[\s\n]+such[\s\n]+monitoring[\s\n]+to[\s\n]+law[\s\n]*enforcement[\s\n]+officials.
var_accounts_user_umask: !!str 027
var_auditd_max_log_file: !!str 6
var_auditd_num_logs: !!str 5
var_auditd_action_mail_acct: !!str root
var_auditd_admin_space_left_action: !!str single
var_auditd_max_log_file_action: !!str rotate
var_removable_partition: !!str /dev/cdrom

aide_update_database: !!bool false
hardening_disable_coredumps: !!bool false
hardening_disable_user_coredumps: !!bool false
