---
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
# file: ansible/roles/docker/tasks/debian.yml

- name: be sure other versions of docker are not present
  apt:
    pkg:
    - docker
    - docker-engine
    - docker.io
    - containerd
    - runc
    state: absent
    update_cache: yes

- name: be sure the docker dependencies are installed
  apt:
    state: latest
    update_cache: yes
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common

- name: be sure the docker gpg key is installed
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg

- name: be sure the docker source list is configured
  template:
    src: docker.list.j2
    dest: /etc/apt/sources.list.d/docker.list

- name: be sure the latest version of docker is installed
  apt:
    state: latest
    update_cache: yes
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
